# Generated by Django 5.2 on 2025-05-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_indian',
            field=models.BooleanField(default=False),
        ),
    ]
